wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.12
    cli_version: 0.17.0
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717088632
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 19
      - 23
      4: 3.8.12
      5: 0.17.0
      8:
      - 4
      - 5
      13: darwin-arm64
learning_rate:
  desc: null
  value: 0.01
