defaults:
  - override / defaults here

dataset:
  file_path: ../data/stock_data/ABBV.csv

wandb:
  project: stock_price_prediction

model:
  name: LSTM
  hidden_dim: 50
  dropout: 0.2
  parameters:
    learning_rate: 0.001
    epochs: 10
    batch_size: 64

training:
  look_back: 60
  validation_split: 0.2
  early_stopping_patience: 5